# Generated by Django 4.2.16 on 2024-09-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdcollectorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='user',
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdcollectorapp.bird')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birdcollectorapp.bird')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
